2021-09-05 17:18:46,320 - no description
2021-09-05 17:18:46,320 - dataset:ml-1m lr1:0.001 lr2:0.0003 kl:0.05 contrast:0.1 batch:1 model_func:fc_att
2021-09-05 17:18:46,320 - Using CUDA:0
2021-09-05 17:18:47,183 - Building net...
2021-09-05 17:18:47,198 - Net build finished.
2021-09-05 17:18:47,199 - User datasets loaded and saved.
2021-09-05 17:18:47,201 - Start training...
2021-09-05 17:18:47,204 - Traceback (most recent call last):
  File "trainMe0904.py", line 299, in <module>
    train()
  File "trainMe0904.py", line 207, in train
    pred, x_real, z_inferred, out_embed = net(batchx)
  File "/home/lab31/anaconda3/envs/lyleeTorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lab31/FreedomLi/ACVAE-PyTorch-main/Federated_train/modelMe0811.py", line 299, in forward
    rnn_out, _ = self.gru(self.embed_dropout(x))
  File "/home/lab31/anaconda3/envs/lyleeTorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lab31/anaconda3/envs/lyleeTorch/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 835, in forward
    self.check_forward_args(input, hx, batch_sizes)
  File "/home/lab31/anaconda3/envs/lyleeTorch/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 229, in check_forward_args
    self.check_input(input, batch_sizes)
  File "/home/lab31/anaconda3/envs/lyleeTorch/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 203, in check_input
    expected_input_dim, input.dim()))
RuntimeError: input must have 3 dimensions, got 2

2021-09-05 17:18:47,204 - Error.
