2021-09-05 18:56:22,398 - no description
2021-09-05 18:56:22,398 - dataset:ml-1m lr1:0.001 lr2:0.0003 kl:0.05 contrast:0.1 batch:1 model_func:fc_att
2021-09-05 18:56:22,398 - Using CUDA:0
2021-09-05 18:56:23,316 - Building net...
2021-09-05 18:56:23,331 - Net build finished.
2021-09-05 18:56:23,331 - User datasets loaded and saved.
2021-09-05 18:56:23,333 - Start training...
2021-09-05 18:56:30,307 - EPOCH:(0/350),STEP:40/2000000,vae:18590.71556854248,kl:47.70236418955028,contrast:326.50426709651947,prior:3768.5765991210938
2021-09-05 18:56:30,308 - Start validating...
2021-09-05 18:58:07,980 - --------------------VALIDATE RESULT--------------------
2021-09-05 18:58:07,980 - HR@1:0.004468068285844398 HR@5:0.022277261724623236 HR@10:0.03353759968624085 HR@20:0.06343671630763044 HR@50:0.12620909404158423 HR@100:0.20429291985647566 
NDCG@1:0.05286708650977792 NDCG@5:0.05218206332143402 NDCG@10:0.04993864900017784 NDCG@20:0.05785025131941889 NDCG@50:0.08040589060487587 NDCG@100:0.10959201544775335 
MRR@1:0.05286708650977792 MRR@5:0.10444702242846102 MRR@10:0.11631153621541426 MRR@20:0.12663682021857867 MRR@50:0.1326129956702599 MRR@100:0.13454779150946597 
2021-09-05 18:58:07,980 - ------------------------HIGHEST RESULT----------------------
2021-09-05 18:58:07,980 - HR@1:0.004468068285844398 HR@5:0.022277261724623236 HR@10:0.03353759968624085 HR@20:0.06343671630763044 HR@50:0.12620909404158423 HR@100:0.20429291985647566 
NDCG@1:0.05286708650977792 NDCG@5:0.05218206332143402 NDCG@10:0.04993864900017784 NDCG@20:0.05785025131941889 NDCG@50:0.08040589060487587 NDCG@100:0.10959201544775335 
MRR@1:0.05286708650977792 MRR@5:0.10444702242846102 MRR@10:0.11631153621541426 MRR@20:0.12663682021857867 MRR@50:0.1326129956702599 MRR@100:0.13454779150946597 
2021-09-05 18:58:10,549 - Traceback (most recent call last):
  File "trainMe0904.py", line 305, in <module>
    train()
  File "trainMe0904.py", line 195, in train
    batchx, batchy, padding, user_id, cur_cnt = train_dict[idx]
KeyError: 6036

2021-09-05 18:58:10,550 - Error.
