2021-09-05 18:54:51,827 - no description
2021-09-05 18:54:51,827 - dataset:ml-1m lr1:0.001 lr2:0.0003 kl:0.05 contrast:0.1 batch:1 model_func:fc_att
2021-09-05 18:54:51,827 - Using CUDA:0
2021-09-05 18:54:52,724 - Building net...
2021-09-05 18:54:52,739 - Net build finished.
2021-09-05 18:54:52,739 - User datasets loaded and saved.
2021-09-05 18:54:52,741 - Start training...
2021-09-05 18:54:59,549 - EPOCH:(0/350),STEP:40/2000000,vae:18590.71556854248,kl:47.70236418955028,contrast:326.50426709651947,prior:3768.5765991210938
2021-09-05 18:54:59,550 - Start validating...
2021-09-05 18:54:59,554 - Traceback (most recent call last):
  File "trainMe0904.py", line 305, in <module>
    train()
  File "trainMe0904.py", line 287, in train
    validate=True, evaluate_users=hyper_params['evaluate_users'])
  File "/home/lab31/FreedomLi/ACVAE-PyTorch-main/Federated_train/evaluator0904.py", line 67, in evaluate
    pred, _, _, _ = net(batchx)
  File "/home/lab31/anaconda3/envs/lyleeTorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lab31/FreedomLi/ACVAE-PyTorch-main/Federated_train/modelMe0811.py", line 299, in forward
    rnn_out, _ = self.gru(self.embed_dropout(x))
  File "/home/lab31/anaconda3/envs/lyleeTorch/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/lab31/anaconda3/envs/lyleeTorch/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 835, in forward
    self.check_forward_args(input, hx, batch_sizes)
  File "/home/lab31/anaconda3/envs/lyleeTorch/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 229, in check_forward_args
    self.check_input(input, batch_sizes)
  File "/home/lab31/anaconda3/envs/lyleeTorch/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 203, in check_input
    expected_input_dim, input.dim()))
RuntimeError: input must have 3 dimensions, got 4

2021-09-05 18:54:59,554 - Error.
